from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard_redirect, name='home'),
    path('dashboard/', views.dashboard_redirect, name='dashboard'),
    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/admin/users/', views.admin_users, name='admin_users'),
    path('dashboard/admin/levels/', views.level_list, name='level_list'),
    path('dashboard/admin/levels/new/', views.level_create, name='level_create'),
    path('dashboard/admin/levels/<int:pk>/', views.level_detail, name='level_detail'),
    path('dashboard/admin/levels/<int:pk>/edit/', views.level_edit, name='level_edit'),
    path('dashboard/admin/levels/<int:pk>/delete/', views.level_delete, name='level_delete'),
    path('dashboard/admin/classes/', views.batch_list, name='batch_list'),
    path('dashboard/admin/classes/new/', views.batch_create, name='batch_create'),
    path('dashboard/admin/classes/<int:pk>/', views.batch_detail, name='batch_detail'),
    path('dashboard/admin/classes/<int:pk>/edit/', views.batch_edit, name='batch_edit'),
    path('dashboard/admin/classes/<int:pk>/delete/', views.batch_delete, name='batch_delete'),
    path('dashboard/admin/classes/<int:pk>/enroll/', views.batch_enroll_student, name='batch_enroll_student'),
    path('dashboard/admin/classes/<int:pk>/unenroll/<int:enrollment_id>/', views.batch_unenroll_student, name='batch_unenroll_student'),
    path('dashboard/admin/accounts/new/', views.admin_create_account, name='admin_create_account'),
    path('dashboard/admin/teachers/', views.teacher_list, name='teacher_list'),
    path('dashboard/admin/teachers/new/', views.teacher_create, name='teacher_create'),
    path('dashboard/admin/teachers/<int:pk>/', views.teacher_detail, name='teacher_detail'),
    path('dashboard/admin/teachers/<int:pk>/edit/', views.teacher_edit, name='teacher_edit'),
    path('dashboard/admin/teachers/<int:pk>/delete/', views.teacher_delete, name='teacher_delete'),
    path('dashboard/admin/students/', views.student_list, name='student_list'),
    path('dashboard/admin/students/new/', views.student_create, name='student_create'),
    path('dashboard/admin/students/<int:pk>/', views.student_detail, name='student_detail'),
    path('dashboard/admin/students/<int:pk>/edit/', views.student_edit, name='student_edit'),
    path('dashboard/admin/students/<int:pk>/delete/', views.student_delete, name='student_delete'),
    path('dashboard/admin/parents/', views.parent_list, name='parent_list'),
    path('dashboard/admin/parents/new/', views.parent_create, name='parent_create'),
    path('dashboard/admin/parents/<int:pk>/', views.parent_detail, name='parent_detail'),
    path('dashboard/admin/parents/<int:pk>/link-student/', views.parent_link_student, name='parent_link_student'),
    path('dashboard/admin/parents/<int:pk>/unlink-student/<int:link_id>/', views.parent_unlink_student, name='parent_unlink_student'),
    path('dashboard/admin/parents/<int:pk>/edit/', views.parent_edit, name='parent_edit'),
    path('dashboard/admin/parents/<int:pk>/delete/', views.parent_delete, name='parent_delete'),
    path('dashboard/teacher/', views.teacher_dashboard, name='teacher_dashboard'),
    path('dashboard/student/', views.student_dashboard, name='student_dashboard'),
    path('dashboard/parent/', views.parent_dashboard, name='parent_dashboard'),
]
