# Generated by Django 5.2.17 on 2026-08-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-is_active', '-enrolled_on']},
        ),
    ]
