# Generated by Django 5.2.17 on 2026-08-20 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_classbatch_end_date_classbatch_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='ended_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('LEFT', 'Left')], default='ONGOING', max_length=20),
        ),
        migrations.CreateModel(
            name='LevelPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_on', models.DateField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('from_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_from', to='accounts.level')),
                ('promoted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_promotions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.studentprofile')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_to', to='accounts.level')),
            ],
            options={
                'ordering': ['-promoted_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('class_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.classbatch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-date', 'student__user__last_name'],
                'constraints': [models.UniqueConstraint(fields=('class_batch', 'student', 'date'), name='unique_attendance_per_class_student_date')],
            },
        ),
    ]
