# Generated by Django 5.2.17 on 2026-08-20 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_enrollment_ended_on_enrollment_status_levelpromotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('node_type', models.CharField(choices=[('SUBJECT', 'Subject'), ('TOPIC', 'Topic'), ('SECTION', 'Section'), ('SUBSECTION', 'Subsection')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_nodes', to='accounts.level')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.curriculumnode')),
            ],
            options={
                'ordering': ['ordering', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.curriculumnode')),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_banks', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='accounts.curriculumnode')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('MULTIPLE_CHOICE', 'Multiple choice')], default='NUMERIC', max_length=20)),
                ('correct_answer', models.CharField(max_length=240)),
                ('options', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.questionbank')),
            ],
            options={
                'ordering': ['difficulty', 'pk'],
            },
        ),
    ]
