# Generated by Django 5.2.17 on 2026-08-20 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_curriculumnode_assignment_questionbank_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('passing_score', models.PositiveSmallIntegerField(default=70)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='accounts.curriculumnode')),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('average_answer_time', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='accounts.studentprofile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.test')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_memberships', to='accounts.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='accounts.test')),
            ],
            options={
                'ordering': ['ordering', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('test', 'question'), name='unique_question_per_test'), models.UniqueConstraint(fields=('test', 'ordering'), name='unique_test_question_order')],
            },
        ),
    ]
