# Generated by Django 5.2.17 on 2026-08-20 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_test_testattempt_testquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_attendance_percent', models.PositiveSmallIntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_activities', to='accounts.assignment')),
                ('class_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.classbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_class_activities', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_activities', to='accounts.test')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MakeupGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_makeup_groups', to=settings.AUTH_USER_MODEL)),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='makeup_groups', to='accounts.classbatch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='makeup_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MakeupGroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.makeupgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_memberships', to='accounts.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='makeupgroup',
            name='students',
            field=models.ManyToManyField(related_name='makeup_groups', through='accounts.MakeupGroupStudent', to='accounts.studentprofile'),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('learning_objective', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('class_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.classbatch')),
                ('curriculum_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to='accounts.curriculumnode')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='accounts.classschedule')),
            ],
            options={
                'ordering': ['-date', 'schedule__start_time'],
                'constraints': [models.UniqueConstraint(fields=('class_batch', 'schedule', 'date'), name='unique_class_session_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='makeupgroupstudent',
            constraint=models.UniqueConstraint(fields=('group', 'student'), name='unique_makeup_group_student'),
        ),
    ]
