# Generated by Django 5.2.17 on 2026-08-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_classactivity_makeupgroup_makeupgroupstudent_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment__isnull', False)), fields=('class_batch', 'assignment'), name='unique_batch_assignment_activity'),
        ),
        migrations.AddConstraint(
            model_name='classactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('test__isnull', False)), fields=('class_batch', 'test'), name='unique_batch_test_activity'),
        ),
    ]
